print("How old are you?", end=' ')
age = input(">")
print("How tall are you?", end=' ')
height = input('>')
print("How much do you weight?", end=' ')
weight = input(">")
print("Are you single ?", end=' ')
single = input("[yes/no] -->")

print(f"So, you're {age} old, {height} tall and {weight} heavy, single: {single}")
